// Canonical Phase 1 customer-facing branding registry
// (docs/PHASE_1_BRANDING_STANDARD.md). Single source of truth for:
//   1. Brand name/subtitle/disclosure strings used OUTSIDE next-intl
//      catalogs (e.g. metadata fallbacks, non-localized report footers).
//   2. The prohibited-term list the branding regression test
//      (test/phase1-branding.test.ts) scans every locale catalog against.
//   3. The old->new terminology map, kept as living documentation of what
//      Phase 1 renamed and why — not itself a runtime replace mechanism.
//
// This does NOT replace next-intl. Actual customer-facing strings still
// live in messages/*.json under normal translation keys; this module is
// the reference/enforcement layer, not a second content system.
//
// Internal implementation identifiers are explicitly OUT of scope and must
// keep their existing names: aiProvider, diagnosticAgent, providerRouter,
// anthropicProvider, openaiProvider, geminiReviewer/geminiProvider,
// chatMessages-shaped local state, DiagnosticAIProvider, etc. Only
// user-visible copy changes.

export const BRAND_NAME = "DTC Technician™";
export const BRAND_SUBTITLE = "Professional Diagnostic Copilot";

// Used in report footers / help content — never a substitute for actually
// blocking an unsafe recommendation (that remains safety-rules.ts's job).
export const BRAND_DISCLOSURE =
  "DTC Technician provides software-assisted diagnostic guidance and is not an in-person technician. Confirm test procedures and repair decisions using appropriate service information and professional judgment.";

export const REPORT_PREPARED_BY_LABEL = `Prepared by ${BRAND_NAME}`;
export const REPORT_TITLE = "Professional Diagnostic Report";

// Regex fragments (word-boundary, case-insensitive) for terms that must not
// appear in ordinary customer-facing translation catalogs. Exceptions
// (never scanned by the regression test, by construction — see
// test/phase1-branding.test.ts's file list): legal/disclosure pages
// (src/app/(app)/{ai-disclaimer,terms,privacy,...}/page.tsx, which are
// plain hardcoded-English components, not sourced from messages/*.json),
// admin/developer screens, and internal documentation/code comments.
export const PROHIBITED_CUSTOMER_FACING_TERM_PATTERNS: RegExp[] = [
  /\bchatbot\b/i,
  /\bchatgpt\b/i,
  /\bgpt\b/i,
  /\bclaude\b/i,
  /\banthropic\b/i,
  /\bopenai\b/i,
  /\bgemini\b/i,
  /\bllm\b/i,
  /model routing/i,
  /\bprompt\b/i,
  /ai[- ]generated/i,
  /\bask ai\b/i,
];

// Documentation of the approved renames — not applied programmatically.
// Each customer-facing surface is updated by hand across the relevant
// translation namespace(s) and component(s); this table is the checklist a
// reviewer (or future contributor) can diff actual copy against.
export const APPROVED_TERMINOLOGY_MAP: ReadonlyArray<{ from: string; to: string }> = [
  { from: "DTC Lookup", to: "Quick Code Lookup" },
  { from: "AI Assistant", to: `${BRAND_NAME}` },
  { from: "AI Technician", to: `${BRAND_NAME}` },
  { from: "AI Agent", to: `${BRAND_NAME}` },
  { from: "AI Chat", to: "Diagnostic Consultation" },
  { from: "Chat", to: "Diagnostic Consultation" },
  { from: "Chat History", to: "Consultation History" },
  { from: "New Chat", to: "New Diagnostic Case" },
  { from: "Resume Chat", to: "Resume Diagnostic Case" },
  { from: "Chat Session", to: "Diagnostic Session" },
  { from: "Conversation", to: "Diagnostic Consultation" },
  { from: "Conversation History", to: "Consultation History" },
  { from: "Conversation Summary", to: "Diagnostic Consultation Summary" },
  { from: "Chat Transcript", to: "Consultation Notes" },
  { from: "AI Report", to: "Professional Diagnostic Report" },
  { from: "AI Diagnostic Report", to: "Professional Diagnostic Report" },
  { from: "AI Analysis", to: "Professional Scan Analysis" },
  { from: "Scan Report Analysis", to: "Professional Scan Analysis" },
  { from: "AI Diagnosis", to: "Professional Diagnosis" },
  { from: "AI Workflow", to: "Guided Diagnosis" },
  { from: "Guided Diagnostic Workflow", to: "Guided Diagnosis" },
  { from: "AI Findings", to: "Diagnostic Findings" },
  { from: "AI Confidence", to: "Diagnostic Confidence" },
  { from: "AI Recommendation", to: "Recommended Diagnostic Direction" },
  { from: "AI Summary", to: "Technician Summary" },
  { from: "AI Explanation", to: "Technician Explanation" },
  { from: "AI Credits", to: "Diagnosis Credits" },
  { from: "AI Usage", to: "DTC Technician Usage" },
  { from: "AI Preferences", to: "Diagnostic Preferences" },
  { from: "Upload Scan", to: "Import Vehicle Scan" },
  { from: "Generated by AI", to: `Prepared by ${BRAND_NAME}` },
];
