-- Canonical AI diagnostic records and their per-locale translations. The
-- English text generated by the AI assistant is always the source of
-- truth (see src/lib/ai/assistant.ts's translateDiagnosticText) — a
-- localization is a faithful translation of that fixed text, never an
-- independently-regenerated diagnostic conclusion. Saving a report is a
-- deliberate, paid, explicit user action (saveDiagnosticReportAction), not
-- automatic per chat turn — most chat turns are exploratory, not something
-- worth persisting/exporting, so auto-saving every message would be
-- unbounded growth with no product signal behind it.

-- Populated by an UPDATE after the AI response stream closes (so it never
-- blocks time-to-first-byte on the live chat). ai_translated_response only
-- gets a value when the request's outputLocale was non-English.
alter table search_history
  add column ai_canonical_response_en text,
  add column ai_translated_response text;

create table diagnostic_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  search_history_id uuid references search_history (id) on delete set null,
  source_message text not null,
  detected_source_language text,
  canonical_locale text not null default 'en' check (canonical_locale = 'en'),
  canonical_text text not null,
  grounding_dtc_code_ids uuid[] not null default '{}',
  model_id text not null,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index diagnostic_reports_user_id_idx on diagnostic_reports (user_id, created_at desc);

create trigger diagnostic_reports_set_updated_at
before update on diagnostic_reports
for each row execute function set_updated_at();

alter table diagnostic_reports enable row level security;
create policy diagnostic_reports_owner_read on diagnostic_reports
  for select using (auth.uid() = user_id);

create table diagnostic_report_localizations (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references diagnostic_reports (id) on delete cascade,
  locale_code text not null references languages (locale_code),
  translated_text text not null,
  translation_status text not null default 'completed'
    check (translation_status in ('pending', 'completed', 'failed')),
  generated_at timestamptz,
  unique (report_id, locale_code)
);

alter table diagnostic_report_localizations enable row level security;
create policy diagnostic_report_localizations_owner_read on diagnostic_report_localizations
  for select using (
    exists (
      select 1 from diagnostic_reports r
      where r.id = report_id and r.user_id = auth.uid()
    )
  );

-- Writes to diagnostic_reports / diagnostic_report_localizations go through
-- the service-role client from saveDiagnosticReportAction — no insert/
-- update/delete policy, matching every other write path in this schema.
